### ISSUE TITLE
Bug: listattedance implicit assumption adding all students to event

### ISSUE THREAD

**Issue by Wnayar** [AY2425S1-CS2103T-W10-1/tp#170]
Type: Functionality bug 

After adding a student to an attendance event, using listattendance for that even and absent, it will show ever other student as absent. This means why you create an event you are implicitly suggesting all students were meant to be a part of it and the default state is absent. Which may be misleading. For example if only 5 student were suppose to belong to event 1. As a teacher, if i filter and see everyone else is absent, I might assume they are part of the event and dint attend. But in actuality they were not suppose to be in the event at all.  In the picture below I had added one student to event 1, and when i check for listattendance of that event it shows everyone else was absent from that event, when they should not be in that event. 

I think its up to you if you want to fix this one, because I can see your argument for the way you implemented it, but your choice. But I will say for not having a UI it can become quite hard to visualize what's happening. 

![image](https://github.com/user-attachments/assets/39d1ddc0-b5d0-4dc8-875e-66fd27677584)

**Comment by ishan-agarwal-05** [comment]
I think it will be too hard to change it now
