### ISSUE TITLE
[PE-D][Tester C] App is inefficient in managing multiple classes

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W10-1/tp#226]
![Screenshot 2024-11-08 at 4.44.02 PM.png](https://raw.githubusercontent.com/wang-h-z/ped/main/files/f68ae922-9771-4b82-a1ae-01984868e663.png)

![Screenshot 2024-11-08 at 4.44.23 PM.png](https://raw.githubusercontent.com/wang-h-z/ped/main/files/9720544e-21d8-4369-83bd-75d51f1889aa.png)

Currently, there is no way to segment students into classes for each `event`, and every student is assumed to be `absent` in every single class. If the TA manages multiple classes, then he/she would see students from other classes in an event, which can be very confusing.

The use of `groups` does not improve this as the `listattn` command cannot be filtered using `groups`.

A suggestion would be to implement a field known as `class` which allows TA's to specify which classes the students are in and `listattn` can filter by these classes.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: wang-h-z/ped#5

**Comment by ishan-agarwal-05** [comment]
Added as planned enhancement number 2 in DG
