### ISSUE TITLE
[PE-D][Tester A] List attendance command usage has a typo

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W10-1/tp#254]
![image.png](https://raw.githubusercontent.com/Edsel-Tan/ped/main/files/5a2e6149-4e4f-42be-9d04-dbf67c3f549d.png)

Should be listattn instead

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Edsel-Tan/ped#8

**Comment by NicholasT1** [comment]
fixed in #263
